
import "./globals.css";
import Navbar from "@/Components/Navbar";
import Footer from "@/Components/Footer";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default  function RootLayout ({ children }) {
  return (
    <html
    data-theme="light"
      lang="en"
    >
      <body className="min-h-full flex flex-col">
        <Navbar></Navbar>
        {children}
        <Footer></Footer>
        </body>
    </html>
  );
}
